version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "perfcona"
      POSTGRES_USER: "perfcona"
      POSTGRES_PASSWORD: "perfcona"
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/pgdata:/var/lib/postgresql/data
      - ./postgresql/2. Init Database:/docker-entrypoint-initdb.d
  pmm-data:
    image: percona/pmm-server:latest
    container_name: pmm-data-percona
    volumes:
      - ./percona/prometheus/data:/opt/prometheus/data
      - ./percona/consul-data:/opt/consul-data
      - ./percona/mysql:/var/lib/mysql
      - ./percona/grafana:/var/lib/grafana
    entrypoint: /bin/true
  pmm-server:
    image: percona/pmm-server:latest
    container_name: pmm-server
    ports:
      - '81:80'
      - '9090:9090'
    restart: always
    environment:
      - SERVER_USER=pefcona
      - SERVER_PASSWORD=pefcona
      - METRICS_RETENTION=720h
      - METRICS_MEMORY=4194304
      - METRICS_RESOLUTION=1s
      - QUERIES_RETENTION=30
    volumes_from:
      - pmm-data