version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "perfcona"
      POSTGRES_USER: "perfcona"
      POSTGRES_PASSWORD: "perfcona"
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/pgdata:/var/lib/postgresql/data
      - ./postgresql/2. Init Database:/docker-entrypoint-initdb.d
  percona:
    image: percona/pmm-server:latest
    ports:
      - "443:443"
    volumes:
      - ./percona/var:/var