version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "perfcona"
      POSTGRES_USER: "perfcona"
      POSTGRES_PASSWORD: "perfcona"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./2. Init Database:/docker-entrypoint-initdb.d